name: desafio_tecnico_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_native_splash: ^2.3.6
  get: ^4.6.6
  google_fonts: ^6.1.0
  mocktail: ^1.0.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  simple_fontellico_progress_dialog: ^0.3.0
  vocsy_epub_viewer: ^2.0.0

flutter_native_splash:
  color: "#4CAF50"
  image: assets/app/splash.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  package_rename: ^1.5.1

package_rename_config:
  android:
    app_name: Desafio Técnico 2

flutter:
  uses-material-design: true

  assets:
    - assets/app/
